#pragma once

#define MAX_FRAME_RATE 240//60 fps se bi giat hinh
#define SCREEN_WIDTH 512
#define SCREEN_HEIGHT 512

#define BACKGROUND_COLOR D3DCOLOR_XRGB(0, 0, 0)
#define BACKGROUND_COLOR2 D3DCOLOR_XRGB(255, 255, 255)

#define GAMEMODE_START 0
#define GAMEMODE_INTRO 1
#define GAMEMODE_GAMERUN 2

#define ID_TEX_CASTLE_CINEMATIC 1
#define ID_TEX_OBJECT_CINEMATIC 2
#define ID_TEX_SIMON_RIGHT 3
#define ID_TEX_SIMON_LEFT 4
#define ID_TEX_SIMON_POTION_RIGHT 5
#define ID_TEX_SIMON_POTION_LEFT 6
#define ID_TEX_DOOR 7
#define ID_TEX_WEAPON_RIGHT 8
#define ID_TEX_WEAPON_LEFT 9
#define ID_TEX_MISC 10
#define ID_TEX_EFFECT 11
#define ID_TEX_BONUS_OBJECT 12
#define ID_TEX_SUBWEAPON_RIGHT 13
#define ID_TEX_SUBWEAPON_LEFT 14
#define ID_TEX_CREEP_RIGHT 15
#define ID_TEX_CREEP_LEFT 16
#define ID_TEX_VAMBAT 17

#define ID_TEX_BLACKBOARD 18
#define ID_TEX_BACKGROUND_START_SCREEN 19
#define ID_TEX_BACKGROUND_INTRO_1 20
#define ID_TEX_BACKGROUND_TILE_MAP 21

#define TILE_SIZE 64

#define SIMON_WALKING_SPEED		0.13f //0.13

#define CAMERA_Y_STAGE_2 448//448
#define CAMERA_X_LEFT 0
#define CAMERA_X_RIGHT_STAGE_0 1039
#define CAMERA_X_RIGHT_STAGE_1 2576
#define CAMERA_X_LEFT_STAGE_2 3072
#define CAMERA_X_RIGHT_STAGE_2 3600
#define CAMERA_X_LEFT_STAGE_3 4096
#define CAMERA_X_RIGHT_STAGE_3 5136